resize_shape: [224, 224]
targets: ['glass', 'metal', 'paper', 'plastic', 'trash']
main_model_path_1: "vgg16_mix_100epoch.h5"
main_model_url_1: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.2/vgg16_mix_100epoch.h5"
main_model_sha256_1: "6f1249d117e2ce9bd7333dc743e347b0d2164ff9e876c02230a2d500fa44acc5"
main_model_path_2: "densenet_mix_100epoch.h5"
main_model_url_2: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.2/densenet_mix_100epoch.h5"
main_model_sha256_2: "4d57d12363483e00fcda1bbfe0627cc8b6807f8c7faf5c85f7f6620a0eaef4d9"
main_model_path_3: "resnet101_mix_100epoch.h5"
main_model_url_3: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.2/resnet101_mix_100epoch.h5"
main_model_sha256_3: "0b06e432b9965b5ee73c9d6f535bf6cc97f4d4c79d76fa523cfe1b80d3d454e9"
main_model_path_4: "mobilenetv2_mix_100epoch.h5"
main_model_url_4: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.2/mobilenetv2_mix_100epoch.h5"
main_model_sha256_4: "4978922320057e2e7d694e14130b2127292b6855a2c57f39a150b202f6a69594"
main_model_path_5: "inceptionv3_mix_100epoch.h5"
main_model_url_5: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.2/inceptionv3_mix_100epoch.h5"
main_model_sha256_5: "9466b829977b1975ae0a9bb23029cf8e0f134ffb833689be6a544fd69420c395"