resize_shape: [224, 224]
targets: ['glass', 'metal', 'paper', 'plastic', 'trash']
model_path: "mymodel_vgg16_rework_30epoch.h5"
model_url: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/Prototype/mymodel_vgg16_rework_30epoch.h5"
model_sha256: "998d38b070d54c469bedab35132cc53a13dab6bbd322637a372d4532e623ffda"
main_model_path_1: "vgg16_newmodel_100epoch.h5"
main_model_url_1: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.0/vgg16_newmodel_100epoch.h5"
main_model_sha256_1: "94a75cb5dc7deafb7836d9c96614f3c59c66da364567ed17a42955e84ec14e18"
main_model_path_2: "densenet_newmodel_100epoch.h5"
main_model_url_2: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.0/densenet_newmodel_100epoch.h5"
main_model_sha256_2: "e04ff64405d55d2bdbec094aa07b67c9a65b762665fc7988a92b68d51f6a8121"
main_model_path_3: "resnet101_newmodel_100epoch.h5"
main_model_url_3: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.0/resnet101_newmodel_100epoch.h5"
main_model_sha256_3: "2299eafa79d9857bb39269548b201e108a66253765a1090524f07d1af59f3f81"
main_model_path_4: "mobilenetv2_newmodel_100epoch.h5"
main_model_url_4: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.0/mobilenetv2_newmodel_100epoch.h5"
main_model_sha256_4: "2647e8d83ee60305fe1c37338c1b80b4af8c08747eb9c49f52977b17f91b9237"
main_model_path_5: "inceptionv3_newmodel_100epoch.h5"
main_model_url_5: "https://github.com/Metalbuster/WasteImageRecognition/releases/download/V1.0/inceptionv3_newmodel_100epoch.h5"
main_model_sha256_5: "913cf57da0f3a6c33499ede03d36ff955c9cfc56381d0e3ff0656105fd811c4b"